repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/tofuutils/pre-commit-opentofu
    rev: v1.0.2
    hooks:
      - id: tofu_fmt
      - id: tofu_validate
      - id: tofu_docs

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/bridgecrewio/checkov
    rev: 3.2.260
    hooks:
      - id: checkov

  - repo: https://github.com/aquasecurity/tfsec
    rev: v1.28.6
    hooks:
      - id: tfsec
